#[colors.bright]
#black = "#928374"
#blue = "#83a598"
#cyan = "#8ec07c"
#green = "#b8bb26"
#magenta = "#d3869b"
#red = "#fb4934"
#white = "#ebdbb2"
#yellow = "#fabd2f"

#[colors.normal]
#black = "#282828"
#blue = "#458588"
#cyan = "#689d6a"
#green = "#98971a"
#magenta = "#b16286"
#red = "#cc241d"
#white = "#a89984"
#yellow = "#d79921"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 16.0

[font.bold]
family = "Ubuntu Mono"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono"
style = "Italic"

[font.normal]
family = "Ubuntu Mono"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 5
y = 5
