#!/bin/sh
dte(){
        dte="$(date +"%a, %b %d %I:%M %p")"
        echo "$dte"
}

hdd(){
        hdd="$(df -h /home | grep dev | awk '{print$3, " "  $5}')"
        echo "HDD: $hdd"
}

mem(){
        mem="$(free -h | awk '/Mem:/ {printf $3 " / " $2}')"
        echo "Mem: $mem"
}

cpu() {
    read cpu a b c previdle rest < /proc/stat
      prevtotal=$((a+b+c+previdle))
        sleep 0.5
          read cpu a b c idle rest < /proc/stat
            total=$((a+b+c+idle))
              cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
                echo " CPU: $cpu% "
}


vol(){
	vol="$(amixer -D pulse get Master | awk -F'[][]' 'END{print $4":"$2}')"
	echo "Volume $vol"
}

kernel(){
	kernel="$(uname -sr | sed "s/-amd64//g")"
	echo $kernel
}


bat() {
	battery="$(cat /sys/class/power_supply/BAT0/capacity)"
	echo "$battery %"
}

batstat() {
	bstat="$(cat /sys/class/power_supply/BAT0/status)"
	echo "$bstat"
}

status(){
	echo "$(cpu) | $(mem) | $(hdd) | $(bat) $(batstat) | $(dte)"
}


while true; do
	xsetroot -name "$(status)"
	sleep 10
done
